---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: '{{.Values.app}}-{{.Values.deploymentgroup}}--hpa-policy'
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: cluster.indeed.com/name
              operator: "In"
              values:
                {{- .Values.apply-rum-proxy.deafult | toYaml | nindent 2 }}
        values:
          env: '{{"{{"}}metadata.labels.cluster.indeed.com/env{{"}}"}}'
  template:
    metadata:
      name: '{{.Values.app}}-{{.Values.deploymentgroup}}-{{"{{"}}name{{"}}"}}--hpa-policy'
    spec:
      project: default
      source:
        repoURL: https://github.com/inder128/argocd-app-config-main.git
        targetRevision: main
        path: charts/hpa-policy
        helm:
          valueFiles:
            - 'values-{{.Values.app}}.yaml'
          values: |
            app: {{.Values.app}}
            deploymentgroup: {{.Values.deploymentgroup}}
            cluster: {{"{{"}}name{{"}}"}}
      destination:
        name: '{{"{{"}}name{{"}}"}}'
        namespace: '{{.Values.app}}--{{"{{"}}values.env{{"}}"}}'
      syncPolicy:
        automated:
          prune: true

          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
