apiVersion: apps/v1
kind: Deployment
metadata:
  name: indeedapply.apply-rum-proxy.default
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 100m
          memory: 500Mi
        
