apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: indeedapply.apply-rum-proxy.default
  namespace: apply-rum-proxy--qa
  labels:
    apps.indeed.com/deployment-group-name: default
    apps.indeed.com/product-group: indeedapply
    apps.indeed.com/project: apply-rum-proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: indeedapply.apply-rum-proxy.default
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
