apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: indeedapply.apply-rum-proxy.default
  labels:
    apps.indeed.com/deployment-group-name: default
    apps.indeed.com/product-group: indeedapply
    apps.indeed.com/project: apply-rum-proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: indeedapply.apply-rum-proxy.default
  minReplicas: {{.Values.autoscaling.minReplicas}}
  maxReplicas: {{.Values.autoscaling.maxReplicas}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{.Values.autoscaling.targetAverageCPUUtilizationPercentage}}
          
