apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apply-rum-proxy--argocd-applicationset
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: cluster.indeed.com/name
              operator: In
              values:
                - awscmhqa3
  template:
    metadata:
      name: 'apply-rum-proxy--argocd-application'
    spec:
      destination:
        name: 'in-cluster'
        namespace: 'apply-rum-proxy--prod'
      project: argo-cd-applications
      source:
        path: charts/hpa-policy
        repoURL: 'https://github.com/inder128/argocd-app-config-main.git'
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
