---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: indeedapply-hpa-policy-argocd-applicationset
spec:
  generators:
    - list:
        elements:
          - app: apply-rum-proxy
  template:
    metadata:
      name: '{{app}}-hpa-policy-argocd-application'
    spec:
      project: argo-cd-applications
      source:
        repoURL: https://github.com/inder128/argocd-app-config-main.git
        targetRevision: main
        path: charts/hpa-policy
      destination:
        name: in-cluster
        namespace: argo-cd-general
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground

