---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: indeedapply-hpa-policy-argocd-applicationset
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: cluster.indeed.com/name
              operator: "In"
              values:
                - awscmhqa3
  template:
    metadata:
      name: 'app-hpa-policy-argocd-application'
    spec:
      project: argo-cd-applications
      source:
        repoURL: https://github.com/inder128/argocd-app-config-main.git
        targetRevision: main
        path: charts/hpa-policy
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground

