---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apply-rum-proxy--argocd-applicationset
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: cluster.indeed.com/name
              operator: "In"
              values:
                - awscmhqa3
  template:
    metadata:
      name: 'apply-rum-proxy--argocd-application--{{name}}'
    spec:
      project: argo-cd-applications
      source:
        repoURL: https://github.com/inder128/argocd-app-config-main.git
        targetRevision: main
        path: charts/apply-rum-proxy
        helm:
          valueFiles:
            - values-{{name}}.yaml
      destination:
        name: '{{name}}'
        namespace: ''
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
