---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: indeedapply--hpa-policy
spec:
  generators:
    - list:
        elements:
          - app: apply-rum-proxy
            deploymentgroup: deafult
  template:
    metadata:
      name: '{{app}}-{{deploymentgroup}}--hpa-policy'
    spec:
      project: default
      source:
        repoURL: https://github.com/inder128/argocd-app-config-main.git
        targetRevision: main
        path: charts/hpa-policy--appset
        helm:
          values: |
            app: {{app}}
            deploymentgroup: {{deploymentgroup}}
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground