# Default values for apply-rum-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

autoscaling:
  minReplicas: 2
  maxReplicas: 5
  targetAverageCPUUtilizationPercentage: 70
