apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: 'indeedapply.{{.Values.app}}.{{.Values.deploymentgroup}}'
  labels:
    apps.indeed.com/deployment-group-name: {{.Values.deploymentgroup}}
    apps.indeed.com/product-group: indeedapply
    apps.indeed.com/project: {{.Values.app}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: 'indeedapply.{{.Values.app}}.{{.Values.deploymentgroup}}'

  minReplicas: '{{.Values.{{.Values.deploymentgroup}}.{{.Values.cluster}}.minReplicas}}'
  maxReplicas: '{{.Values.{{.Values.deploymentgroup}}.{{.Values.cluster}}.maxReplicas}}'

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{.Values.targetAverageCPUUtilizationPercentage}}

  behavior:
    scaleUp:
      policies:
        - type: Percent
          value: 25
          periodSeconds: 15
        - type: Pods
          value: '{{.Values.{{.Values.deploymentgroup}}.{{.Values.cluster}}.scaleUp.pods}}'
          periodSeconds: 15
      selectPolicy: Max
      stabilizationWindowSeconds: 0

    scaleDown:
      policies:
        - type: Pods
          value: '{{.Values.{{.Values.deploymentgroup}}.{{.Values.cluster}}.scaleDown.pods}}'
          periodSeconds: 300
      stabilizationWindowSeconds: 600
