{{- $app := .Values.app -}}
{{- $deploymentgroup := .Values.deploymentgroup -}}
{{- $cluster := .Values.cluster -}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: 'indeedapply.{{$app}}.{{$deploymentgroup}}'
  labels:
    apps.indeed.com/deployment-group-name: {{$deploymentgroup}}
    apps.indeed.com/product-group: indeedapply
    apps.indeed.com/project: {{$app}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: 'indeedapply.{{$app}}.{{$deploymentgroup}}'

  minReplicas: {{index .Values $deploymentgroup $cluster "minReplicas"}}
  maxReplicas: {{index .Values $deploymentgroup $cluster "maxReplicas"}}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{.Values.targetAverageCPUUtilizationPercentage}}

  behavior:
    scaleUp:
      policies:
        - type: Percent
          value: 25
          periodSeconds: 15
        - type: Pods
          value: {{index .Values $deploymentgroup $cluster "scaleUp" "pods"}}
          periodSeconds: 15
      selectPolicy: Max
      stabilizationWindowSeconds: 0

    scaleDown:
      policies:
        - type: Pods
          value: {{index .Values $deploymentgroup $cluster "scaleDown" "pods" }}
          periodSeconds: 300
      stabilizationWindowSeconds: 600
